# Generated by Django 3.1.3 on 2020-12-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanchonetes', '0004_auto_20201130_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.CharField(max_length=200),
        ),
    ]
